apiVersion: v2
name: pfv2
description: PTESFinder v2 - annotation-free backsplice junction identification from RNA-seq
type: application
version: 0.1.0
appVersion: "2.2.0"
home: https://github.com/osagiei/pfv2
maintainers:
  - name: Osagie Izuogu
    email: osagie.izuogu@gmail.com
